





# POST http://localhost:3000/api/projects/newproject HTTP/1.1
GET http://localhost:3000/api HTTP/1.1

content-type: application/json
{
    "name": "Openbud",
    "gitlink": "aijdiasjdoij",
    "owner": "owner",
    "contributors": ["Vikranth"],
    "icon": "none",
    "description": "Best project in the world"
}